webserver:
  build: images/webserver
  ports:
    - "80:80"
  links:
    - mysql:mysql
  volumes_from:
    - app

app:
  image: busybox
  volumes:
    - "./sites/app/app.conf:/etc/nginx/sites-enabled/app.conf"
    - "./app/:/var/www/"

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    ON_CREATE_DB: "apidb"


